### ISSUE TITLE
High CPU utilisation due to membership-manager docker.

### ISSUE THREAD

**Issue by mahajanankur** [citusdata/docker#186]
I found the membership-manager docker is utilising a lot CPU due to which master and workers are also heating up the environment.

**Comment by hanefi** [comment]
Thanks @mahajanankur for reporting this. 

I created two PRs that aims to resolve this issue:
1. https://github.com/citusdata/membership-manager/pull/9 implements a polling mechanism in Membership Manager, so that (a) it will detect the readiness of the coordinator node, (b) properly report that it is ready to accept new Citus worker services
2. https://github.com/citusdata/docker/pull/187 (a) updates the docker images to properly detect dependencies, (b) introduce Compose V3 definitions

Once they are merged, this issue should be resolved

**Comment by mahajanankur** [comment]
@hanefi, just to inform you, the issue is still there even after shutting down the **membership-manager** container.

![citus_stats_2](https://user-images.githubusercontent.com/7963490/79121052-01702980-7db2-11ea-9f58-877ce3d7729f.png)
